DROP DATABASE IF EXISTS auth; 
CREATE DATABASE auth;
USE auth;

DROP TABLE IF EXISTS users; 
CREATE TABLE users (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL DEFAULT '',
email VARCHAR (250) NOT NULL DEFAULT '', 
phone VARCHAR(25) NOT NULL DEFAULT '',
password VARCHAR (200) NOT NULL DEFAULT '',
avatar VARCHAR(200) DEFAULT '',
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;